#!/usr/bin/env bun
/**
 * Propagate API keys from the central store (~/.config/mk-agent/env)
 * into the repo-local .env.local files that Bun auto-loads.
 *
 * Single source of truth: ~/.config/mk-agent/env (synced from hub).
 * This script writes ONLY the project-relevant keys into two locations:
 *   • ./.env.local                     (repo root — CLI, scripts)
 *   • ./packages/server/.env.local     (server package)
 *
 * Run after any `sync-keys` or after editing the central file. Typical
 * flow when rotating a key:
 *   1. Paste the new value into ~/.config/mk-agent/env (or update on hub).
 *   2. `sync-keys` (PowerShell) to pull from hub if edited there.
 *   3. `bun scripts/pull-keys.ts` to fan out to .env.local files.
 *
 * Bun treats process.env as having priority, so when PowerShell profile
 * has already populated env, .env.local is a redundant fallback for
 * non-PowerShell shells (Docker, WSL, CI). Keeping them in sync prevents
 * the "it works in PowerShell but not Docker" drift class.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { homedir } from 'node:os';

// Keys the project actually consumes. Anything in the central file
// that isn't on this list stays out of the repo's .env.local files.
const PROJECT_KEYS = [
  'GEMINI_API_KEY',
  'FAL_KEY',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
] as const;

// Where to write. All paths are repo-relative (cwd assumed = repo root).
const TARGETS = [
  '.env.local',
  'packages/server/.env.local',
];

const CENTRAL = resolve(homedir(), '.config', 'mk-agent', 'env');

function readCentral(path: string): Map<string, string> {
  if (!existsSync(path)) {
    throw new Error(`Central env file not found: ${path}\nRun sync-keys (PowerShell) or create the file.`);
  }
  const text = readFileSync(path, 'utf8');
  const entries = new Map<string, string>();
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const m = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(trimmed);
    if (!m) continue;
    entries.set(m[1]!, m[2]!);
  }
  return entries;
}

function writeTarget(path: string, values: Record<string, string>): void {
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const body = [
    '# Auto-generated by scripts/pull-keys.ts — do NOT edit by hand.',
    '# Source of truth: ~/.config/mk-agent/env',
    '# Regenerate:     bun scripts/pull-keys.ts',
    '',
    ...Object.entries(values).map(([k, v]) => `${k}=${v}`),
    '',
  ].join('\n');
  writeFileSync(path, body, 'utf8');
}

const central = readCentral(CENTRAL);

const resolved: Record<string, string> = {};
const missing: string[] = [];
const empty: string[] = [];
for (const key of PROJECT_KEYS) {
  const val = central.get(key);
  if (val === undefined) {
    missing.push(key);
    resolved[key] = '';
  } else if (val === '') {
    empty.push(key);
    resolved[key] = '';
  } else {
    resolved[key] = val;
  }
}

for (const target of TARGETS) {
  writeTarget(target, resolved);
  console.log(`wrote ${target}`);
}

const present = PROJECT_KEYS.filter((k) => resolved[k] && resolved[k] !== '');
console.log(`\npopulated: ${present.join(', ') || '(none)'}`);
if (empty.length) console.log(`empty:     ${empty.join(', ')}`);
if (missing.length) console.log(`missing:   ${missing.join(', ')}`);
