/**
 * Character retex — swap a GLB material's base-color texture.
 *
 * First-pass implementation focuses on the 99% case: Quaternius-style
 * characters bake their whole outfit into one diffuse atlas on a single
 * material. Swap that texture and the character gets a new uniform without
 * touching UVs or vertex data. Region-aware LUT retex (separate skin vs
 * uniform zones) is a future enhancement — deferred per proposal §P5 scope.
 *
 * For batch faction retex (OG-107, ERDL, tiger-stripe, khaki, black-pajama),
 * the caller generates five preset diffuse PNGs once per base character (via
 * the sprite pipeline or hand-authored) and feeds them through this function
 * as `diffuse` buffers.
 */

import { Buffer } from 'node:buffer';
import { readFileSync } from 'node:fs';

import { NodeIO, type Material } from '@gltf-transform/core';

export interface RetexCharacterOptions {
  /** New base-color PNG bytes (or path to a PNG on disk). */
  diffuse: Buffer | string;
  /** Target material by its glTF name. First match wins. */
  materialName?: string;
  /**
   * Target material by 0-based index in doc.listMaterials(). Ignored if
   * materialName is set.
   */
  materialIndex?: number;
  /**
   * Label stored in the output meta for provenance (e.g. 'OG-107-jungle').
   * Does not affect the GLB itself.
   */
  presetName?: string;
}

export interface RetexCharacterResult {
  glb: Buffer;
  meta: {
    materialName: string;
    materialIndex: number;
    bytes: number;
    sourceBytes: number;
    presetName?: string;
  };
}

export async function retexCharacter(
  input: Buffer | string,
  opts: RetexCharacterOptions,
): Promise<RetexCharacterResult> {
  const srcBuf = typeof input === 'string' ? readFileSync(input) : input;
  const diffuseBytes =
    typeof opts.diffuse === 'string' ? readFileSync(opts.diffuse) : opts.diffuse;

  const io = new NodeIO();
  const doc = await io.readBinary(srcBuf);
  const materials = doc.getRoot().listMaterials();
  if (!materials.length) {
    throw new Error('retexCharacter: GLB has no materials to retex');
  }

  const { material, index } = selectMaterial(materials, opts);

  // Reuse the existing base-color texture if present; otherwise create one.
  let texture = material.getBaseColorTexture();
  if (!texture) {
    texture = doc.createTexture(`${material.getName() || 'mat'}_baseColor`);
    material.setBaseColorTexture(texture);
  }
  texture.setImage(new Uint8Array(diffuseBytes));
  texture.setMimeType('image/png');

  const outBytes = await io.writeBinary(doc);
  const glb = Buffer.from(outBytes);

  return {
    glb,
    meta: {
      materialName: material.getName(),
      materialIndex: index,
      bytes: glb.byteLength,
      sourceBytes: srcBuf.byteLength,
      ...(opts.presetName ? { presetName: opts.presetName } : {}),
    },
  };
}

function selectMaterial(
  materials: Material[],
  opts: RetexCharacterOptions,
): { material: Material; index: number } {
  if (opts.materialName) {
    const idx = materials.findIndex((m) => m.getName() === opts.materialName);
    if (idx < 0) {
      throw new Error(
        `retexCharacter: no material named "${opts.materialName}" (available: ${materials
          .map((m) => m.getName() || '(unnamed)')
          .join(', ')})`,
      );
    }
    return { material: materials[idx]!, index: idx };
  }
  if (typeof opts.materialIndex === 'number') {
    const idx = opts.materialIndex;
    if (idx < 0 || idx >= materials.length) {
      throw new Error(
        `retexCharacter: materialIndex ${idx} out of bounds (have ${materials.length})`,
      );
    }
    return { material: materials[idx]!, index: idx };
  }
  // Default: first material (Quaternius pattern — one atlas per character).
  return { material: materials[0]!, index: 0 };
}

/**
 * Known faction preset names. These are labels for provenance — this module
 * does NOT ship the baked diffuse PNGs; the caller provides them. Presets
 * are expected to be generated by the sprite pipeline once per base model
 * and cached alongside the source GLB.
 */
export const FACTION_PRESETS = [
  'OG-107-jungle',
  'ERDL-leaf',
  'tiger-stripe',
  'khaki-plain',
  'black-pajama',
] as const;
export type FactionPreset = (typeof FACTION_PRESETS)[number];
